name: Checkstyle

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  checkstyle:
    name: Run Checkstyle
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Checkstyle
        uses: dbelyaev/action-checkstyle@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
          checkstyle_config: google_checks.xml

  discord:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Discord Commits
          uses: Sniddl/discord-commits@v1.6
          with:
            webhook: ${{ secrets.DISCORD_WEBHOOK }}
            template: "avatar-with-link"
            include-extras: true
